### ISSUE TITLE
JS - Movie Display Function

### ISSUE THREAD

**Issue by rolanduwxcc** [rolanduwxcc/project-bmw#5]
* Accepts a JSON object
* Gets the movie data out
* Creates the HTML to display on side one

**Comment by blee2013** [comment]
Pull this Information: 

1. Title
2. Released
3. Actors
4.  Director
5.  Ratings | Rotten Tomatoes

- Plot --> "Description"
- Poster--> "Pink Image"

**Comment by blee2013** [comment]
Done
