### ISSUE TITLE
JS - Call the news function

### ISSUE THREAD

**Issue by rolanduwxcc** [rolanduwxcc/project-bmw#6]
* Accepts a search string
* Fetches JSON data from a news API
* Passes the JSON object to a HTML Display function for News data

**Comment by rolanduwxcc** [comment]
Should we just feed the search string with the first actor in the data, right?

**Comment by blee2013** [comment]
Pull this Information: 

- 1. Title
- 2. Released
- 3. Actors
- 3. Director
- 5. Ratings | Rotten Tomatoes

- Plot --> "Description"
- Poster--> "Pink Image"
